project:
  type: website

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

website:
  title: "Savika Singh Mandhata"
  navbar:
    background: primary
    search: true
    left:
      - text: "Projects"
        file: projects.qmd
      - text: "Additional Experiences"
        file: additional-experiences.qmd
      
    tools:
      - icon: twitter
        href: https://twitter.com/savika_10
      - icon: github
        href: https://github.com/savika10
      - icon: linkedin
        href: https://www.linkedin.com/in/savika10/
  
  sidebar:
    - title: "Projects"
      style: "floating"
      contents: 
        - projects.qmd
        - section: "Computer Vision"
          contents: projects/CV/*
        - section: "NLP"
          contents: projects/NLP/*
        - section: "Time-series"
          contents: projects/Time-series/*
        - section: "Robotics"
          contents: projects/Robotics/*
        - section: "Kaggle"
          contents: projects/Kaggle/*
          
    - title: "Publications"
      style: "floating"
      contents: 
        - publications.qmd
        - section: "Publications"
          contents: publications/*

execute:
  freeze: auto
